BINARY = main
SRCFILES = main.c 1ra_capa/unsere_gpio.c 1ra_capa/unsere_uart.c 1ra_capa/unsere_rcc.c 2da_capa/led.c 2da_capa/button.c 2da_capa/unsere_log.c 3ra_capa/stopwatch.c

all: elf bin

include ../../Makefile.incl
